<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-28 14:48
=======
# Generated by Django 4.2.6 on 2023-10-28 11:07
>>>>>>> c5c40991717f0d88f5b75616fd44c3e362b4c6ca

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
