# Generated by Django 4.2.7 on 2023-11-26 10:38

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "booksfinal.json")

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20231126_0943'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
