# Generated by Django 4.2.6 on 2023-10-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20231028_1616'),
        ('catalog', '0003_auto_20231028_1658'),
    ]

    operations = [
    ]
